# Generated by Django 5.2.3 on 2025-06-17 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('codigo_sku', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=20)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso en kilogramos', max_digits=8, null=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo_sku'], name='productos_p_codigo__9a5e79_idx'), models.Index(fields=['categoria', 'estado'], name='productos_p_categor_4e40bd_idx'), models.Index(fields=['created_at'], name='productos_p_created_797da5_idx')],
            },
        ),
    ]
